apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    deployment-config.name: broker
    
  name: broker
  namespace: helios
spec:
  ports:
  - name: "mgmt"
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: "rabbitmq"
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    deployment-config.name: broker
  type: ClusterIP
status:
  loadBalancer: {}
