apiVersion: v1
data:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_VHOST: /
  RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rabbitmq
  namespace: helios
