apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    deploymentconfig: nginx
  name: helios-nginx
  namespace: helio
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deploymentconfig: nginx
  type: NodePort
status:
  loadBalancer: {}
