apiVersion: v1
kind: PersistentVolume
metadata:
  name: helios-ngconf
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 100Mi
  nfs:
    server: 172.17.1.136
    path: /share/nfs/okd/helios/nginx/conf
