apiVersion: v1
kind: PersistentVolume
metadata:
  name: helios-pgvol
spec:
  accessModes: ["ReadWriteOnce"]
  nfs:
    server: 172.17.1.136
    path: /share/nfs/okd/helios/postgres
  capacity:
    storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helios-pgclaim
  namespace: helio
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
