apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: heliosdb
  name: postgres-svc
  namespace: helio
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: heliosdb
  type: ClusterIP
status:
  loadBalancer: {}
